apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${BRANCH}-detour
spec:
  selector:
    matchLabels:
      app: ${BRANCH}-detour
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ${BRANCH}-detour
    spec:
      containers:
        - name: ${BRANCH}-detour
          image: ${CONTAINER_REPO}:detour-${BRANCH}-${GITHUB_SHA}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ${BRANCH}-detour
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ${BRANCH}-detour

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ${BRANCH}-detour
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: ${BRANCH}-detour.api.viggo.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${BRANCH}-detour
            port:
              number: 80