apiVersion: apps/v1
kind: Deployment
metadata:
  name: $BRANCH
  labels:
    hash: $GITHUB_SHA
spec:
  selector:
    matchLabels:
      app: $BRANCH
  replicas: 1
  template:
    metadata:
      labels:
        app: $BRANCH
    spec:
      containers:
        - name: $BRANCH
          image: $CONTAINER_REPO:$BRANCH-$GITHUB_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: $BRANCH
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: $BRANCH

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: $BRANCH
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: $BRANCH.api.viggo.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: $BRANCH
                port:
                  number: 80
